// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

//sandbox_manufactura
const SUPABASE_URL = "https://jdqeefaefbukrcqbvbnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkcWVlZmFlZmJ1a3JjcWJ2Ym5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NDk0MjQsImV4cCI6MjA2OTMyNTQyNH0.kjV1XpjSgfxTMyiIDlw40iFAtm5k88mvFdG5PzIiMXg";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});