// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

//sandbox_manufactura
const SUPABASE_URL = "https://bkfpcuvrpfaxuwzvultb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrZnBjdXZycGZheHV3enZ1bHRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDU2NjksImV4cCI6MjA3MzAyMTY2OX0.64dCOA1l1Gn1IS8vT0nwAgQJxTlMJvqEHo3sf-iI9QA";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});